/**
 * Audit log action identifiers.
 * Grouped by domain for readability.
 */
export const AuditAction = {
  // Authentication
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_2FA_ENABLED: 'AUTH_2FA_ENABLED',
  AUTH_2FA_DISABLED: 'AUTH_2FA_DISABLED',
  AUTH_PASSKEY_REGISTERED: 'AUTH_PASSKEY_REGISTERED',
  AUTH_PASSKEY_REMOVED: 'AUTH_PASSKEY_REMOVED',

  // Account
  ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',

  // API Keys
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_ROTATED: 'API_KEY_ROTATED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',

  // Webhooks
  WEBHOOK_CREATED: 'WEBHOOK_CREATED',
  WEBHOOK_UPDATED: 'WEBHOOK_UPDATED',
  WEBHOOK_DELETED: 'WEBHOOK_DELETED',

  // Cloud / Storage
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_DELETED: 'FILE_DELETED',
  FILE_MOVED: 'FILE_MOVED',
  DIRECTORY_CREATED: 'DIRECTORY_CREATED',
  DIRECTORY_DELETED: 'DIRECTORY_DELETED',

  // Team
  TEAM_CREATED: 'TEAM_CREATED',
  TEAM_MEMBER_INVITED: 'TEAM_MEMBER_INVITED',
  TEAM_MEMBER_REMOVED: 'TEAM_MEMBER_REMOVED',
  TEAM_ROLE_CHANGED: 'TEAM_ROLE_CHANGED',
  TEAM_OWNERSHIP_TRANSFERRED: 'TEAM_OWNERSHIP_TRANSFERRED',

  // Subscription
  SUBSCRIPTION_CHANGED: 'SUBSCRIPTION_CHANGED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
