export enum CaslAction {
  Manage = 'manage',
  Create = 'Create',
  Read = 'Read',
  Update = 'Update',
  Delete = 'Delete',
  Upload = 'Upload',
  Download = 'Download',
  Extract = 'Extract',
  Archive = 'Archive',
  Execute = 'Execute',
}

export enum CaslSubject {
  All = 'all',
  User = 'User',
  Subscription = 'Subscription',
  MySubscription = 'MySubscription',
  Cloud = 'Cloud',
  CloudDirectory = 'CloudDirectory',
  CloudUpload = 'CloudUpload',
  CloudArchive = 'CloudArchive',
  Account = 'Account',
  Session = 'Session',
  Passkey = 'Passkey',
  TwoFactor = 'TwoFactor',
  ApiKey = 'ApiKey',
  Definition = 'Definition',
  Team = 'Team',
  TeamMember = 'TeamMember',
  TeamInvitation = 'TeamInvitation',
  TeamCloud = 'TeamCloud',
  TeamCloudDirectory = 'TeamCloudDirectory',
  TeamCloudUpload = 'TeamCloudUpload',
  TeamCloudArchive = 'TeamCloudArchive',
}
