export enum NotificationType {
  // Cloud / Storage
  UPLOAD_COMPLETE = 'UPLOAD_COMPLETE',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  FILE_DELETED = 'FILE_DELETED',
  FILE_MOVED = 'FILE_MOVED',

  // Archive
  ARCHIVE_CREATE_PROGRESS = 'ARCHIVE_CREATE_PROGRESS',
  ARCHIVE_CREATE_COMPLETE = 'ARCHIVE_CREATE_COMPLETE',
  ARCHIVE_CREATE_FAILED = 'ARCHIVE_CREATE_FAILED',
  ARCHIVE_EXTRACT_PROGRESS = 'ARCHIVE_EXTRACT_PROGRESS',
  ARCHIVE_EXTRACT_COMPLETE = 'ARCHIVE_EXTRACT_COMPLETE',
  ARCHIVE_EXTRACT_FAILED = 'ARCHIVE_EXTRACT_FAILED',

  // Quota
  QUOTA_WARNING = 'QUOTA_WARNING',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',

  // Team
  TEAM_INVITATION_RECEIVED = 'TEAM_INVITATION_RECEIVED',
  TEAM_INVITATION_ACCEPTED = 'TEAM_INVITATION_ACCEPTED',
  TEAM_INVITATION_DECLINED = 'TEAM_INVITATION_DECLINED',

  // Subscription
  SUBSCRIPTION_CHANGED = 'SUBSCRIPTION_CHANGED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',

  // Errors
  ERROR = 'ERROR',
  RATE_LIMIT = 'RATE_LIMIT',
}
